<?xml version="1.0" ?>

<!DOCTYPE Depts [
	<!ELEMENT Depts (Dept+)>
	<!ELEMENT Dept (name, Emp*, budget?)>
		<!ATTLIST Dept dno ID #REQUIRED>
		<!ATTLIST Dept mgr IDREF #IMPLIED>
	<!ELEMENT budget (#PCDATA)>
	<!ELEMENT Emp (name)>
		<!ATTLIST Emp eno ID #REQUIRED>
	<!ELEMENT name (#PCDATA)>
]>

<Depts>
	<Dept dno = "D1">
		<name>Management</name>
		<Emp eno="E7"><name>R. Davis</name></Emp>
		<Emp eno="E8"><name>J. Jones</name></Emp>		
	</Dept>
	<Dept dno = "D2" mgr = "E7">
		<name>Consulting</name>
		<Emp eno="E6"><name>L. Chu</name></Emp>
		<Emp eno="E3"><name>A. Lee</name></Emp>
		<budget>350000</budget>
	</Dept>
</Depts>

